version: 2.1
orbs:
  newman: postman/newman@0.0.1
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./json_collection/Training.postman_collection.json
          environment: ./env/LAMP-staging.postman_environment.json